export { default as Branches } from './images/branches.png'
export { default as bulbImg } from './images/banner_1.png'
export { default as chairImg } from './images/sofa promotional header.png'
export { default as bannerSub } from './images/Group 153.png'
export { default as rectangle } from './images/Rectangle 102.png'
export { default as notFound } from './images/404.png'
export { default as contact } from './images/Group 73.png'
export { default as sale } from './images/sale.png'
export { default as check } from './images/Vector 15.png'
export { default as oclock } from './images/Group.png'
export { default as checklist } from './images/checklist 1.png'
export { default as profileShop } from './images/Screenshot 2023-04-22 163823.png'
export { default as banner } from './images/Green Creative Save Our Earth Banner.png'
export { default as banner2 } from './images/33791098.jpg'
export { default as logo1 } from './images/1.png'
export { default as logo2 } from './images/2.png'
export { default as logo3 } from './images/3.png'
export { default as logo4 } from './images/4.png'
export { default as bannerHome } from './images/Home.png'
export { default as event1 } from './images/event1.png'

export { default as event2 } from './images/event2.png'

export { default as event3 } from './images/event3.jpg'

export { default as event4 } from './images/event4.jpg'
